- app/models/user.rb
- db/migrate/20150127162929_change_table_users_column_presenter_set_default.rb
- db/migrate/20150127170148_change_table_users_change_column_name_presenter.rb
- db/schema.rb
- test/models/user_test.rb
Add basic testing of users table. No null values for key fields, default value of false for presenter column. Changed name of presenter? field to presenter.
> Model test

- test/models/question_test.rb
Test for null text.
Test for null user_id.
Test for successful save if text and user_id are present.
> Add basic tests for Questions model.

- test/models/user_test.rb
Add test to check for two users being saved with the same email.
Modify completeness test to use actual boolean false instead of string "false"
> Add test for duplicate email in users.

- app/assets/javascripts/application.js
- app/assets/javascripts/table.js
- app/assets/stylesheets/table.css
- app/views/users/index.html.erb
adds current and past lecture tables with links to question index as placeholder
> Student landing

- app/views/questions/index.html.erb
Added link to question text on index page
Fixed table left-margin to match show page.
> Add link to question show page from question index.

- app/views/questions/new.html.erb
Added hidden field and id of current_user to enable adding new questions.
<%= f.hidden_field :user_id, value:current_user.id %>
This closes issue #35.
> Fix add question issue#35

- test/models/question_test.rb
> Modify to properly test questions.

- app/controllers/questions_controller.rb
- app/views/questions/show.html.erb
This fixes display of votes for answers on show page.
> Fix voting display for answers on show page

- test/models/vote_test.rb
> Modify - cleanup of code

- app/controllers/questions_controller.rb
- app/views/questions/index.html.erb
fixed bug on front-end where routes were dead, bug on back-end calling answers on newly created questions
> fix minor bugs with last push

- app/views/questions/index.html.erb
- app/views/questions/show.html.erb
Added basic voting views to index page.  Fixed links to show page.  Added link from show page back to questions index page.
> Basic voting views added to index.  Fixed broken Links.  Added link from Show to Idx on Q.

- app/models/answer.rb
> Add validation of text, check for presence of text. Fixes issue #60.

- test/test_helper.rb
> Add needed devise test helper include to test_helper.rb. Fixes issue #66

- test/controllers/users_controller_test.rb
- test/fixtures/answers.yml
- test/fixtures/questions.yml
- test/fixtures/votes.yml
> Add data to all text fixtures. Fixes issue #76

- app/controllers/users_controller.rb
- test/controllers/users_controller_test.rb
> Modify Users controller to make proper lookup for destroy method.

- app/controllers/questions_controller.rb
> Comment out binding.pry. Fixes 122

- app/assets/stylesheets/application.css
- app/assets/stylesheets/live-audience-view.css
- app/assets/stylesheets/questionindex.css
- app/views/questions/_button.html
- vendor/assets/stylesheets/lavish-bootstrap.css
Changes made to update the view of the ask new question page
> Update ask question page

- app/controllers/answers_controller.rb
- test/controllers/answers_controller_test.rb
- test/controllers/questions_controller_test.rb
Answer controller tests => green.
> Answer controller test

- Gemfile
- Gemfile.lock
Enables the ability to push and deploy to heroku
> Modify gemfile for use with heroku.

- vendor/assets/stylesheets/lavish-bootstrap.css
also - changed lavish file to new color scheme.
closes #139
> fix glyphicon paths and answer fonts

- vendor/assets/stylesheets/lavish-bootstrap.css
> fix glyphicons and asset pipeline

- app/views/users/index.html.erb
> change color (panel-success to panel-info)
